### ISSUE TITLE
The user should be able to pick different characters

### ISSUE THREAD

**Issue by mortlun** [ezet/tdt4240-asteroids#25]

**Comment by ezet** [comment]
Do we have any suggestions for specific characters?

**Comment by mortlun** [comment]
We could just edit the sprites we use to different colors?

**Comment by mortlun** [comment]
I have made 4 characters and added them to game assets.

**Comment by sakerchr** [comment]
Added simple logic to support this in the Assets-class as well as a separate settings view where you can select between them. Closing the issue as we now have a viable implementation of this.
